global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["pgexp-pgcore:9187", "pgexp-pgdialog:9187", "pgexp-pgauth:9187"]
  - job_name: social-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["social-auth:8080", "social-post:8080", "social-core:8080", "sonet-dialog:8080"]