spring:
  application:
    name: social-post
  main:
    cloud-platform: kubernetes
  cloud:
    kubernetes:
      config:
        enabled: true
      reload:
        enabled: true
        monitoring-config-maps: true
        strategy: refresh
        mode: event