{
 "title": "RPS_Latency_Errors",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"/actuator/prometheus\"}[20s])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LATENCY 50-95-99-MAX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(http_server_requests_seconds_bucket{uri!~\"/actuator/prometheus\"}[60s])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_requests_seconds_bucket{uri!~\"/actuator/prometheus\"}[60s])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_requests_seconds_bucket{uri!~\"/actuator/prometheus\"}[60s])) by (le))"
    },
    {
     "expr": "histogram_quantile(1,sum(rate(http_server_requests_seconds_bucket{uri!~\"/actuator/prometheus\"}[60s])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\", status=~\"4.+|5.+\"}[1m])) / sum(increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[1m]))"
    }
   ]
  }
 ]
}